version: "3"

services:
  api:
    image: mateenali66/api:latest
    container_name: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - /home/mateen/app/api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    image: mateenali66/client:latest
    container_name: client
    volumes:
      - /home/mateen/app/client:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  db:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - '/home/mateen/app/db/init:/docker-entrypoint-initdb.d/'


volumes:
  node_modules:
